# SPDX-License-Identifier: GPL-2.0

ifneq ($(CONFIG_DEVICE_MODULES_ALLOW_BUILTIN),y)

LINUXINCLUDE := $(DEVCIE_MODULES_INCLUDE) $(LINUXINCLUDE)

subdir-ccflags-y += -Wall -Werror \
		-I$(srctree)/$(src)/include \
		-I$(srctree)/$(src)/include/uapi \

obj-y += drivers/memory/
obj-y += drivers/pinctrl/mediatek/
obj-y += drivers/iommu/
obj-y += drivers/input/keyboard/
obj-y += drivers/spi/
obj-y += drivers/reset/

obj-y += drivers/edac/

obj-y += drivers/iio/adc/

obj-y += drivers/mfd/

obj-y += drivers/nvmem/

obj-y += drivers/dma/mediatek/

obj-y += drivers/ufs/

obj-y += drivers/char/

obj-y += drivers/clk/mediatek/

obj-y += drivers/soc/mediatek/

obj-y += drivers/regulator/

obj-y += drivers/leds/

obj-y += drivers/power/supply/

obj-y += drivers/rtc/

obj-y += drivers/remoteproc/

# xaga: platform module wiring (mtk_rpmsg_mbox exports mtk_rpmsg_create_channel/
# create_device for mtk_tinysys_ipi)
obj-y += drivers/rpmsg/

obj-y += drivers/thermal/mediatek/

obj-y += drivers/spmi/

obj-y += drivers/tty/serial/8250/

obj-y += drivers/mailbox/

obj-y += drivers/interconnect/

obj-y += drivers/i2c/busses/

obj-y += drivers/pwm/

obj-y += drivers/mmc/host/

obj-y += drivers/tee/

# xaga: platform module wiring (mtu3 exports ssusb_get_drvdata for ps5170)
obj-y += drivers/usb/

# xaga: USB PHYs (tphy/u2port0-u3port0, xsphy, ufs) - mtu3 needs
# phy-mtk-tphy for its `phys = <&u2port0>, <&u3port0>` refs; without a PHY
# driver mtu3 defers -> no UDC -> fastbootd "couldn't find an available
# UDC" -> recovery auto-reboots (real-device, 2026-08-11)
obj-y += drivers/phy/

obj-y += drivers/gpu/drm/mediatek/

obj-y += drivers/input/misc/
obj-y += drivers/input/touchscreen/

obj-y += drivers/gpu/drm/panel/

obj-y += drivers/gpu/drm/bridge/

obj-y += drivers/gpu/mediatek/

obj-y += drivers/media/platform/

obj-y += drivers/net/ethernet/stmicro/

obj-y += drivers/net/phy/

obj-y += drivers/devfreq/

# xaga: platform module wiring (system_heap exports dma_buf_get_gid for mediatek-drm)
obj-y += drivers/dma-buf/heaps/

obj-y += drivers/misc/mediatek/dcm/
obj-y += drivers/misc/

obj-y += sound/soc/codecs/

obj-y += sound/soc/mediatek/

obj-y += sound/virtio/

obj-y += drivers/pci/controller/

obj-y += drivers/media/virtio/

obj-y += drivers/video/backlight/

endif
