# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_MEDIATEK_MT6362_ADC) += mt6362-adc.o

# xaga: platform module wiring
obj-m += mt6375-adc.o

# xaga: platform module wiring
obj-m += mt6375-auxadc.o

# xaga: platform module wiring
obj-m += mtk-spmi-pmic-adc.o
