# SPDX-License-Identifier: GPL-2.0
#
# Makefile for HW Random Number Generator (RNG) device drivers.
#

#obj-$(CONFIG_HW_RANDOM_SECURE) += sec-rng.o

# xaga: platform module wiring
obj-m += sec-rng.o
