# SPDX-License-Identifier: GPL-2.0
obj-m += pd_dbg_info.o

# xaga: platform module wiring
obj-m += rt_pd_manager.o

# xaga: platform module wiring
obj-m += tcpci_late_sync.o

# xaga: platform module wiring
obj-m += tcpc_mt6375.o
