ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/sda/include
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/aee/aed/
ccflags-y += -I$(srctree)/kernel/


# xaga: platform module wiring
obj-m += cache-parity.o

# xaga: platform module wiring
obj-m += dbgtop-drm.o

# xaga: platform module wiring
obj-m += irq-dbg.o
