# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the 8250 serial device drivers.
#
#ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/tty/serial/8250

#obj-$(CONFIG_DEVICE_MODULES_SERIAL_8250_MT6577)	+= 8250_mtk.o

# xaga: platform module wiring
obj-m += 8250_mtk.o
