load("//build/bazel_mgk_rules:mgk_ddk_ko.bzl", "define_mgk_ddk_ko")
load("@mgk_info//:kernel_version.bzl","kernel_version",)

package(
    default_visibility = [
        "//visibility:public",
    ],
)

filegroup(
	name = "srcs",
	srcs = glob([
		"**/Makefile",
		"**/Kbuild",
		"**/*.c",
		"**/*.h",
	]),
)

define_mgk_ddk_ko(
    name = "nt36672c",
    srcs = [
        "nt36xxx.c",
        "nt36xxx_ext_proc.c",
        "nt36xxx_fw_update.c",
        "nt36xxx_mp_ctrlram.c",
    ],
    hdrs = glob(["**/*.h"]),
    includes = ["include"],
    copts = [
        "-Wall",
        "-Werror",
        "-I$(DEVICE_MODULES_PATH)/drivers/gpu/drm/mediatek/mediatek_v2/",
    ],
	ko_deps = [
		"//kernel_device_modules-{}/drivers/gpu/drm/mediatek/mediatek_v2:mtk_disp_notify".format(kernel_version),
		"//kernel_device_modules-{}/drivers/gpu/drm/mediatek/mediatek_v2:mediatek-drm".format(kernel_version),
	],
)
