# SPDX-License-Identifier: GPL-2.0
#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y				+= mediatek/
obj-$(CONFIG_MI_HARDWARE_ID)	+= hwid/
obj-$(CONFIG_SIMTRAY_STATUS)	+= simtray.o
obj-$(CONFIG_XAGA_OOPS_LOG)	+= xaga_oops_log.o
obj-$(CONFIG_XAGA_MARKER_WRITER) += xaga-marker-writer.o
